name: Deploy on Docker Publish Success

on:
  workflow_run:
    workflows: ["Publish Docker image"]  # Название workflow, который нужно отслеживать
    types: 
      - completed  # Триггер при завершении workflow
    branches: 
      - main 

jobs:
  deploy:
    runs-on: self-hosted 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Stop and remove the current container
      run: |
        sudo docker stop my_devops_portfolio || true
        sudo docker rm my_devops_portfolio || true

    - name: Pull latest image of my-devops-portfolio
      run: sudo docker pull lord222/my-devops-portfolio:latest

    - name: Recreate my-devops-portfolio container
      run: |
        sudo docker run -d \
          --name my_devops_portfolio \
          -p 3001:80 \
          --restart always \
          lord222/my-devops-portfolio:latest