name: Publish Docker image

on:
  push:
    branches: [ main ]  # Или любую другую ветку, на которую вы хотите автоматизировать сборку и публикацию
  # Работает также и для pull_request, если это необходимо
  # pull_request:
  #   branches: [ main ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: lord222/my-devops-portfolio:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
